// Code generated by go generate on 2018-04-10 05:59:54.828419881 +0000 UTC
package basic



func IdBool(v bool) bool {return v}

func IdByte(v byte) byte {return v}

func IdComplex128(v complex128) complex128 {return v}

func IdComplex64(v complex64) complex64 {return v}

func IdFloat32(v float32) float32 {return v}

func IdFloat64(v float64) float64 {return v}

func IdInt(v int) int {return v}

func IdInt16(v int16) int16 {return v}

func IdInt32(v int32) int32 {return v}

func IdInt64(v int64) int64 {return v}

func IdInt8(v int8) int8 {return v}

func IdRune(v rune) rune {return v}

func IdString(v string) string {return v}

func IdUInt(v uint) uint {return v}

func IdUInt16(v uint16) uint16 {return v}

func IdUInt32(v uint32) uint32 {return v}

func IdUInt64(v uint64) uint64 {return v}

func IdUInt8(v uint8) uint8 {return v}

func IdUintPtr(v uintptr) uintptr {return v}
